const {chromium}=require('playwright');const fs=require('fs'),path=require('path'),http=require('http'),assert=require('assert/strict');
const server=http.createServer((q,r)=>{const js=q.url==='/comparison.js';r.setHeader('Content-Type',js?'application/javascript':'text/html');r.end(fs.readFileSync(path.join(__dirname,js?'../comparison.js':'../index.html')));});
(async()=>{await new Promise(r=>server.listen(0,'127.0.0.1',r));const b=await chromium.launch({channel:'msedge',headless:true});try{const p=await b.newPage({viewport:{width:1440,height:900}}),errors=[];p.on('pageerror',e=>errors.push(e.message));await p.goto('http://127.0.0.1:'+server.address().port);await p.waitForFunction(()=>document.getElementById('plot')._fullLayout);
await p.evaluate(()=>{document.getElementById('minMz').value='200';document.getElementById('maxMz').value='450';document.getElementById('clickMz').checked=true;renderPlot();});await p.waitForTimeout(400);
const baseline=await p.evaluate(()=>captureCurrentAxisRanges());
async function zoom(){await p.evaluate(()=>Plotly.relayout('plot',{'xaxis.range':[280,330],'yaxis.range':[0,40]}));}
async function check(){await p.waitForTimeout(400);assert.deepEqual(await p.evaluate(()=>captureCurrentAxisRanges()),baseline);}
for(const final of [false,true]){await p.evaluate(final=>{document.getElementById('previewExport').checked=final;updateFinalSizePreview(true);},final);await p.waitForTimeout(250);await zoom();const point=await p.evaluate(()=>{const el=document.getElementById('plot'),r=el.getBoundingClientRect(),l=el._fullLayout;return {x:r.x+(l.margin.l+.6*l._size.w)*r.width/l.width,y:r.y+(l.margin.t+.6*l._size.h)*r.height/l.height};});await p.mouse.dblclick(point.x,point.y);await check();await zoom();await p.locator('[data-title="Reset zoom to configured ranges"]').click({force:true});await check();}
await p.evaluate(()=>Plotly.relayout('plot',{'xaxis.autorange':true,'yaxis.autorange':true}));await check();assert.deepEqual(errors,[]);console.log('PASS: real double-click and toolbar restore configured axis ranges in both preview modes with m/z selection enabled; autorange preserves configured limits.');
}finally{await b.close();server.close();}})().catch(e=>{console.error(e);server.close();process.exitCode=1;});